language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - cd final_task
  - pip install .
  - nosetests --cover-branches --with-coverage .
  - pycodestyle --ignore=W605 --max-line-length=120 .
  - python ./../pycalc_checker.py
  - python ./test_main.py
  - cd -
